services:
  haithamportfolio:
    build: .
    hostname: haithamportfolio
    ports:
      - "8080:8080"
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUTH0_CLIENT_ID=n95rvXcxkIKA2AvbpSRsq6qtO1AfNmz8
      - AUTH0_CLIENT_SECRET=8LiVL-8zJnCfyl0wt33DiZcxabzEkVfzFnLt3CxQLMtQL4eZyGu-99xbcsheR_1s
    depends_on:
      - mongodb
      
  haithamPortfolioFE:
    image: haitham-portfolio-fe
    container_name: haitham-portfolio-fe
    build:
      context: ../haitham-portfolio-fe
      dockerfile: Dockerfile
      args:
      - BUILD_MODE=development
    ports:
      - "3000:3000"
    volumes:
      - ../haitham-portfolio-fe/src:/app/src


  mongodb:
    image: mongo
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
  #      healthcheck:
  #        test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
  #        retries: 5
  #        interval: 15s
  #        start_period: 30s

  mongo-express-haithamportfolio:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - 8085:8081