server.port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG


spring:
  data:
    mongodb:
      username: user
      password: pwd
      host: localhost
      port: 27017
      database: haithamportfolio
      authentication-database: admin
      auto-index-creation: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

okta:
  oauth2:
    issuer: https://dev-3bhgduaasaz1xonw.us.auth0.com
    audience: https://dev-3bhgduaasaz1xonw.us.auth0.com/api/v2/

auth0:
  domain: dev-3bhgduaasaz1xonw.us.auth0.com
  clientId: ${AUTH0_CLIENT_ID}
  clientSecret: ${AUTH0_CLIENT_SECRET}
  audience: https://dev-3bhgduaasaz1xonw.us.auth0.com/api/v2/
---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: haithamportfolio
      username: root
      password: password
      authentication-database: admin

